### ISSUE TITLE
Compiling v1.2.0 on CentOS 7 :: linking with `cc` failed

### ISSUE THREAD

**Issue by Kerwood** [tonarino/innernet#64] opened 2021-05-02 17:53 UTC
I'm trying to compile the client binary on CentOS 7 with `cargo install --path client`, but I'm running into below error when compiling `wgctrl-sys`.

```
error: linking with `cc` failed: exit code: 1
```
The full error can be seen here: https://gist.githubusercontent.com/Kerwood/623f446f03447659721cf97861ec56a1/raw/0fd33a7a2d038cb7562e9ec7f7ee3c6b59ac0432/gistfile1.txt

Besides Rust, I've installed `clang-devel` `sqlite-devel`  and `llvm-devel`.

Am I missing something ?

**Comment by mcginty** [comment] 2021-05-08 07:08
I'm not familiar with CentOS's package situation, but from the error it looks like you're missing clang - maybe `clang-devel` doesn't explicitly include it?

**Comment by mcginty** [comment] 2021-05-09 12:19
I don't know if this helps, but maybe the CI RPM specs are useful? https://github.com/tonarino/innernet/blob/main/client/.rpm/innernet.spec

As of this latest beta, we now distribute pre-built RPMs, as well.

**Comment by Kerwood** [comment] 2021-05-09 19:13
It looks like its only building for Cent 8 and Fedora 32+ https://github.com/tonarino/innernet/blob/426916faddbef47923d787fec97479644d8c4fde/.github/workflows/release-artifacts.yml#L81

Its a bit of an issue since WireGuard does not support CentOS 8 Stream and CentOS 8 goes EOL December 31, 2021. Which only leaves CentOS 7 left (EOL 2024), which that RPM package does not support because of glibc-2.17.

It would really be awesome if we could figure out how to compile innernet on CentOS 7.

**Comment by mcginty** [comment] 2021-05-09 19:23
I see - out of curiosity, have you tried building against the musl target (`x86_64-unknown-linux-musl`)?

**Comment by mcginty** [comment] 2021-05-09 19:57
Actually, I think your issue is probably that you're on Clang 3.4, while bindgen expects at least 3.7 (https://rust-lang.github.io/rust-bindgen/requirements.html#clang).

This might be resolved (and speed up build) if we pre-generate bindgen files for wgctrl-sys, as it's less likely to cause issues and not likely to change much at this point.

**Comment by Kerwood** [comment] 2021-05-10 06:29
> I see - out of curiosity, have you tried building against the musl target (`x86_64-unknown-linux-musl`)?

I'm very new to Rust and did not know about `x86_64-unknown-linux-musl` but it looked like a good idea.
So on Fedora 32, I installed `musl-gcc` and installed `x86_64-unknown-linux-musl` target with below command.
```
rustup target add x86_64-unknown-linux-musl --toolchain=nightly
```
And tried to compile it with:
```
cargo build --release --bin innernet --target x86_64-unknown-linux-musl
```

Unfortunately wgctrl-sys is still causing some issues.

```
$ cargo build --release --bin innernet --target x86_64-unknown-linux-musl
   Compiling serde_json v1.0.64
   Compiling toml v0.5.8
   Compiling ipnetwork v0.17.0 (https://github.com/mcginty/ipnetwork#d3316d44)
   Compiling wgctrl-sys v1.2.0 (/home/kerwood/Downloads/innernet/wgctrl-sys)
The following warnings were emitted during compilation:

warning: c/wireguard.c:10:10: fatal error: linux/genetlink.h: No such file or directory
warning:    10 | #include <linux/genetlink.h>
warning:       |          ^~~~~~~~~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `wgctrl-sys v1.2.0 (/home/kerwood/Downloads/innernet/wgctrl-sys)`

Caused by:
  process didn't exit successfully: `/home/kerwood/Downloads/innernet/target/release/build/wgctrl-sys-97087c9bef37a358/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-musl")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CC_x86_64-unknown-linux-musl = None
  CC_x86_64_unknown_linux_musl = None
  TARGET_CC = None
  CC = None
  CROSS_COMPILE = None
  CFLAGS_x86_64-unknown-linux-musl = None
  CFLAGS_x86_64_unknown_linux_musl = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Werror" "-o" "/home/kerwood/Downloads/innernet/target/x86_64-unknown-linux-musl/release/build/wgctrl-sys-9d32f3a89c3e117b/out/c/wireguard.o" "-c" "c/wireguard.c"
  cargo:warning=c/wireguard.c:10:10: fatal error: linux/genetlink.h: No such file or directory
  cargo:warning=   10 | #include <linux/genetlink.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr


  error occurred: Command "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Werror" "-o" "/home/kerwood/Downloads/innernet/target/x86_64-unknown-linux-musl/release/build/wgctrl-sys-9d32f3a89c3e117b/out/c/wireguard.o" "-c" "c/wireguard.c" with args "musl-gcc" did not execute successfully (status code exit status: 1).
``` 

Not sure what `linux/genetlink.h` is though.

**Comment by mcginty** [comment] 2021-05-11 01:47
That just means that you don't have the musl linux headers, maybe something like https://centos.pkgs.org/7/forensics-x86_64/musl-devel-1.2.1-1.el7.x86_64.rpm.html.

That said, I'm pretty sure the problem is your clang version as required by bindgen at this point. I'll work on adding pre-generated bindings.

**Comment by Kerwood** [comment] 2021-05-11 11:49
> That said, I'm pretty sure the problem is your clang version as required by bindgen at this point. I'll work on adding pre-generated bindings.

Awesome, that sounds great.

I am thougt a bit curious on compiling a `musl` binary, but I am still facing that issue I've posted. `musl-devel` was already installed and so are below packages.

```
Package kernel-devel-5.11.18-100.fc32.x86_64 is already installed.
Package kernel-headers-5.11.16-100.fc32.x86_64 is already installed.
Package musl-clang-1.2.1-1.fc32.x86_64 is already installed.
Package musl-devel-1.2.1-1.fc32.x86_64 is already installed.
Package musl-gcc-1.2.1-1.fc32.x86_64 is already installed.
Package musl-libc-static-1.2.1-1.fc32.x86_64 is already installed.
Package musl-libc-1.2.1-1.fc32.x86_64 is already installed.
```
I have used all my Google-foo and cant find anything about `genetlink.h` missing. Any help would be appreciated.

**Comment by Kerwood** [comment] 2021-05-11 18:37
Right. I finally got it compiled against the `musl` target. Apparently, If you use crates which link against C, then you need a full C cross-compilation setup too. The recommended way to cross-compile for `musl` when you need C dependencies is using [Cross](https://github.com/rust-embedded/cross)

I created a `Dockerfile` with below content.
```
FROM rustembedded/cross:x86_64-unknown-linux-musl-0.2.1
RUN apt-get update && \
    apt-get install -y clang libsqlite3-dev libclang-8-dev llvm-8-dev
```

Build the container.
```
docker build -t cross:innernet-musl .
```

Create a file named `Cross.toml` with the following content.
```

**Comment by mcginty** [comment] 2021-05-17 14:45
Thanks for reporting back @Kerwood! I'm sure that information will prove useful for others too. I'll close this issue since it seems resolved.

**Closed by mcginty** 2021-05-17 14:45 UTC
