### ISSUE TITLE
Documentation says Ubuntu/Debian .DEB files are the Release section 

### ISSUE THREAD

**Issue by bmullan** [tonarino/innernet#227] opened 2022-07-19 21:59 UTC
Documentation says...

> Innernet consists of two binaries: innernet-server, the coordinating server, and innernet (also aliased as inn for easy access), the client that peers run to access the network.
> 
> First, let's [install ](https://github.com/tonarino/innernet#installation)[innernet-server](https://github.com/tonarino/innernet#installation) on a server we have sitting around, create a new network, and start it up:
> 
> First, let's install innernet-server on a server we have sitting around, create a new network, and start it up ...

But I do not see any releases w .DEB files just source and tar.gz **_except in the BETA releases_**

Do the .DEB files exist and if so where are they...

thanks
brian

**Comment by bschwind** [comment] 2022-07-21 08:31
Hi @bmullan , 

See the issue [here](https://github.com/tonarino/innernet/issues/203#issuecomment-1069520125) for the current status on *.deb files.

We should fix up the documentation for sure.

You can generate the deb files on the machine you plan to use them with:

```bash
cargo install cargo-deb # if it isn't installed already
cargo deb -p client
cargo deb -p server
```

Assuming you have `cargo` installed. If you don't, you can install it from [rustup.rs](https://rustup.rs/)

**Comment by bschwind** [comment] 2022-07-21 08:31
Closing as a duplicate of #212, but feel free to comment here if you need any help generating the files.

**Closed by bschwind** 2022-07-21 08:31 UTC
