### ISSUE TITLE
Allow for associations based on IP without having to be an active peer

### ISSUE THREAD

**Issue by finnje** [tonarino/innernet#52] opened 2021-04-15 15:23 UTC
I've created an association between CIDRs: `192.168.1.0/24 and 192.168.250.1/32` which should allow any IP address in `192.168.1.0/24 to communicate with `192.168.250.1` however...that only works if the incoming IP is an active innernet peer.

I'd like to be able to have a local subnet (192.168.1.0/24) with devices on it and have a single innernet peer in that subnet say `192.168.1.254`.  Currently that peer can talk to `192.168.250.1` as expected.

If I change the default gateway on the subnet to be `192.168.1.254` and enable ip forwarding on that host then all traffic from other devices make it to the innernet peer but they can't get to `192.168.250.1` unless I add a MASQUERADE and nat the traffic.

That would be fine in some use cases, but I'd like to be able to specify specific device IP's on my local subnet to have associations with specific innernet-peers without them having to have innernet installed on them.

**Comment by mcginty** [comment] 2021-04-17 03:00
Thanks for the issue!

I believe this would be a duplicate of https://github.com/tonarino/innernet/issues/22, please re-open if you disagree!

**Closed by mcginty** 2021-04-17 03:00 UTC
